### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wabilin** [wabilin/holo-subscription#1]
- [x] List subscription
- [x] Clear old lives data
- [ ] Vtuber name alias
- [ ] better daily notification timing?
- [x] check db key do not have `/`, `.`
- [ ] User timezone (?)
- [ ] Unsubscribe all (?)
